### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by patkan** [fau-fablab/fablab-document#1]
CC-BY-SA? Muss noch gesetzt werden

**Comment by mgmax** [comment]
ohne Logo ja.

**Comment by mgmax** [comment]
Drehbankeinweisung hat jetzt einen Baustein, der aus der Vorlage kommt.
Muss man jetzt nur noch in alle anderen Einweisungen einbauen (und dort fablab-document aktualisieren).

**Comment by sedrubal** [comment]
@mgmax warum ohne Logo? Und welcher Baustein?

**Comment by mgmax** [comment]
Das FAU Logo hat sehr wirres Copyright und ist deshalb nichtmal auf 
Wikipedia zu finden. Ich habe echt besseres zu tun, als mir dazu 
Workarounds zu überlegen. 
https://de.wikipedia.org/wiki/Diskussion:Friedrich-Alexander-Universit%C3%A4t_Erlangen-N%C3%BCrnberg#Uni-Logo

Lizenzbaustein: ganz hinten in der Drehbankeinweisung: 
`\ccLicense{drehbank-einweisung}{Einweisung Drehbank}`, erzeugt einen 
freundlichen Text plus das für den Rechtsanwalt :)

**Comment by sedrubal** [comment]
"Merkwürdigerweise scheint die Uni Erlangen-Nürnberg die Rechte an ihrem eigenen Logo nämlich verkauft zu haben" - K.K. :D

Ok, wo ist denn ein Uni Logo?

Den Baustein kann ich einfügen, wenn keienr mag

**Comment by sedrubal** [comment]
erledigt... Wegen solchen Aktionen wäre der Ansatz, eine Buildumgebung zu haben und da die einzelnen Einweisungen als submodule hinzuzufügen eig. schöner...
