### ISSUE TITLE
PDF erscheint immer doppelt

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/fablab-document#3]
Wenn man das Makefile lokal ausführt, erscheint das fertige PDF immer einmal im Ordner `output` aber auch noch einmal im "root" Ordner (da wo das Makefile und das Tex liegt)

**Comment by mgmax** [comment]
ja, so ist das gedacht.

**Comment by sedrubal** [comment]
achso, warum?

**Comment by mgmax** [comment]
nunja, der buildserver kann beliebige makefiles und Ausgaben und braucht daher ein Verzeichnis output. Der Normalnutzer mit tex-Editor erwartet das PDF aber genau da wo das tex liegt.

**Comment by sedrubal** [comment]
ja ok
